# ---------------------------------------------------------------------------
# Walker/Bot protection
# ---------------------------------------------------------------------------

# Basic protection against L2Walker.
# Default: True
L2WalkerProtection = True
